написание функции сложения
js-tasks-ru/js-20210427_dosug pull request #1
Opened 2021-05-02 13:59 UTC by Vinurlan

возврат результата сложения двух аргументов функции.

2021-05-02 13:59 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-05-04 10:01 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return a.localeCompare(b);
пожалуйста обратите внимание на параметры `localeCompare` 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
особенно на параметр `caseFirst`

2021-05-04 10:02 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return arr.slice().sort((a, b) => {
возможно следует вынести копирование массива за пределы условных конструкций, ведь новый массив нам нужен в обоих случаях.
Альтернативный способ копирования массива:
```
const copy = [...arr]
```

2021-05-04 10:03 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
good 👍

2021-05-04 10:03 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).forEach(item => {
good 👍

2021-05-04 10:03 UTC, dosandk requested changes
попробуйте модифицировать решение `sortStrings`

2021-05-06 12:33 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    newArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-05-06 12:33 UTC, dosandk requested changes
решение `sortStrings` нужно доработать

2021-05-10 19:37 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return newArr.sort((a, b) => {
давайте избавимся от дубликатов кода, ведь в строка 11-13 происходит все тоже самое как в строках 17-19, за исключением порядка аргументов `a` и `b`

2021-05-10 19:37 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const arPath = path.split('.');
👍  like за использование замыкания

2021-05-10 19:38 UTC, dosandk approved these changes
good 👍  посмотрите комментарий к решению `sortStrings`

2021-05-10 19:39 UTC, merged